apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app-welcome
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: app-welcome
  template: 
    metadata: 
      labels:
        app: app-welcome
    spec:
      containers:
        - name: app-welcome
          image: k3d-mycluster-registry:5000/welcome_image:v0.1 
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
          ports: 
          - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata: 
  name: app-welcome-svc
spec: 
  selector: 
    app: app-welcome
  ports: 
  - protocol: TCP
    port: 9091
    targetPort: 9091
