[tool.shrinkwrap]
requirements_file = "requirements.txt"
output_path = "build_output"

[tool.shrinkwrap.build]
module_name = "welcome"
scripts = ["start_test.sh"]

[build-system]
requires = ["shrinkwrap"]
build-backend = "shrinkwrap.build"

[tool.black]
line-length = 99
target_version = ['py38']
